config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
    
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :user
  
  belongs_to :book

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
  # before_action :favorite_sort, only: [:update, :destroy]
    
  def create
     
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    
    favorite_sort
    
  end
        
    
  def destroy
    
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    
    favorite_sort
      
  end
  
  private
  
  def favorite_sort
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
    sort_by { |x| x.favorited_users.includes(:favorites).where(created_at: from...to).size }.reverse
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true, style: "color: red;" do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post,remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "/favorites/favorites", book: @book) %>");
$('#index_books').html("<%= j(render "books/index", books: @books) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "/favorites/favorites", book: @book) %>");
$('#index_books').html("<%= j(render "books/index", books: @books) %>");