config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
    
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  
  has_many :book_comments, dependent: :destroy
  
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  
  has_many :followers, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  
  has_many :followeds, through: :passive_relationships, source: :follower
  
  
  has_many :entries, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  
  has_many :rooms, through: :entries
  
  has_many :read_counts, dependent: :destroy
  
  
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  
  def following_by?(user)
    passive_relationships.find_by(follower_id: user.id).present?
  end
  
  def self.search_for(search,word)
    if search == 'perfect'
      User.where(name: word)
    elsif search == 'forward'
      User.where('name LIKE ?', word + '%')
    elsif search == 'backward'
      User.where('name LIKE ?', '%' + word)
    else
      User.where('name LIKE ?', '%' + word + '%')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u| 
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @books = @user.books
    @book = Book.new
    
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
    
  def follows
    user = User.find(params[:id])
    @users = user.followers
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.followeds
  end
    

  def daily_posts
  
    user = User.find(params[:user_id])
    
    if params[:created_at] == ""
    @search_book = "日付を選択してください"
    render :daily_posts_form
    else
    @search_book = user.books.where(created_at: params[:created_at].to_date.all_day).count
    render :daily_posts_form
    end

  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_index.html.erb
<h3>投稿数の前日比・前週比</h3>
<table class= "table table-bordered">
  <tr>
    <th>今日の投稿数</th>
    <th>前日の投稿数</th>
    <th>前日比</th>
  </tr>
  <tr>
    <td><%= @today_book.count %></td>
    <td><%= @yesterday_book.count %></td>
    <td>
      <% if @yesterday_book.count == 0 %>
        前日の投稿はありません
      <% else %>
        <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
        <%= ( @the_day_before * 100).round %>
      <% end %>
    </td>
  </tr>
</table>
<table class= "table table-bordered">
  <tr>
    <th>今週の投稿数</th>
    <th>前週の投稿数</th>
    <th>前週比</th>
  </tr>
  <tr>
    <td><%= @this_week_book.count %></td>
    <td><%= @last_week_book.count %></td>
    <td>
      <% if @last_week_book.count == 0 %>
        前週の投稿はありません
      <% else %>
        <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
        <%= ( @the_week_before * 100).round %>
      <% end %>
    </td>
  </tr>
</table>
<h3>7日間分の投稿数</h3>
<table class= "table table-bordered">
  <tr>
    <th>6日目</th>
    <th>5日目</th>
    <th>4日目</th>
    <th>3日目</th>
    <th>2日目</th>
    <th>1日目</th>
    <th>今日</th>
  </tr>
  <tr>
    <td><%= @books.created_6days.count %></td>
    <td><%= @books.created_5days.count %></td>
    <td><%= @books.created_4days.count %></td>
    <td><%= @books.created_3days.count %></td>
    <td><%= @books.created_2days.count %></td>
    <td><%= @books.created_yesterday.count %></td>
    <td><%= @books.created_today.count %></td>
  </tr>
</table>
<canvas id="myLineChart"></canvas>
<script>
$(document).on('turbolinks:load', function() {
  var ctx = document.getElementById("myLineChart");
  var myLineChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
      datasets: [
        {
          label: '投稿した本の数',
          data: [
            <%= @books.created_6days.count %>,
            <%= @books.created_5days.count %>,
            <%= @books.created_4days.count %>,
            <%= @books.created_3days.count %>,
            <%= @books.created_2days.count %>,
            <%= @books.created_yesterday.count %>,
            <%= @books.created_today.count %>
          ],
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)",
          tension: 0.4
        }
      ],
    },
    options: {
      title: {
        display: true,
        text: '7日間の投稿数の比較'
      },
      responsive: true,
      scales: {
        y:{
          suggestedMin: 0,
          suggestedMax: 10
        },
        x:{
          stacked: true
        },
      },
    }
  });
});
</script>

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.active_relationships.count %></td>
        <td>フォローワー数:<%= user.passive_relationships.count %></td>
        <% if current_user != user %>
          <% if user.following_by?(current_user) %>
            <td><%= link_to "フォロー外す", user_relationships_path(user), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user), method: :post %></td>
          <% end %>
        <% end %>
        
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.active_relationships.count, follows_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.passive_relationships.count, followers_user_path(user) %></th>
  </tr>
  <tr>
    <th>
      <% if current_user != user %>
        <% if user.following_by?(current_user) %>
          <%= link_to "フォローを外す", user_relationships_path(user), method: :delete, class: "btn btn-info" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
        <% end %>
      <% end %>  
    </th>
    <th>
      <%= render "users/room", user: user, isRoom: isRoom, room: room, roomId: roomId, entry: entry %>
    </th>
  </tr>
  
  
</table>
　
<div class='row'>
  <% if current_user != user %>
    <% else %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% end %>
</div>

app/views/users/_room.html.erb
<% if user != current_user %>
  <% if (current_user.following_by?(user)) && (user.following_by?(current_user)) %>
    <% if isRoom == true %>
      <%= link_to "Chatを始める", room_path(roomId) %>
    <% else %>
      <%= form_with model: room do |f| %>
        <%= fields_for entry do |e| %>
          <%= e.hidden_field:user_id, value: user.id %>
        <% end %>
        <%= f.submit "Room作成", class: "btn btn-primary user-show-chat" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
    
        
    

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @search_book ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.empty? %>
  <span>ユーザーはいません</span>
<% else %>
  <table class = "table">
    <thead>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: "50x50" %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.active_relationships.count %></td>
          <td>フォロワー数:<%= user.passive_relationships.count %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>   
<% end %>  

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<% if @users.empty? %>
  <span>ユーザーはいません</span>
<% else %>
<table class= "table">
  <thead>
    <th>image</th>
    <th>name</th>
    <th ></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.active_relationships.count %></td>
        <td>フォロワー数:<%= user.passive_relationships.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      
      <%= render 'info', user: current_user, isRoom: @isRoom, room: @room, roomId: @roomId, entry: @entry %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
      
      </div>
      
      <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, isRoom: @isRoom, room: @room, roomId: @roomId, entry: @entry %>
      <!--< render "users/room", user: @user %>-->
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <%= render "daily_posts_form", user: @user %>
      <%= render "book_index", books: @books %>
    </div>
  </div>
</div>