config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
    
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :book_comments, dependent: :destroy
  
  has_many :read_counts, dependent: :destroy
  
  validates :title,presence:true
  
  validates :body,presence:true,length:{maximum:200}
  
  
  def favorited_by?(user)
    
    favorites.exists?(user_id: user.id)
    
  end
  
  def self.search_for(search,word)
    if search == 'perfect'
      Book.where(title: word)
    elsif search == 'forward'
      Book.where('title LIKE ?', word + '%')
    elsif search == 'backward'
      Book.where('title LIKE ?', '%' + word)
    else
      Book.where('title LIKE ?', '%' + word + '%')
    end
  end
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) } 
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) } 
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) } 
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) } 
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) } 

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
    
    unless ReadCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, book_id: @book.id) 
      @read_count = ReadCount.new(user_id: current_user.id, book_id: @book.id)
      @read_count.save
      # current_user.read_counts.create(book_id: @book.id)　※↑２行省略するとこうできる
      
      
    end
    
  end

  def index
    
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort_by { |x| x.favorited_users.includes(:favorites).where(created_at: from...to).size }.reverse
      
    @book = Book.new
    # @books = Book.all
    @books_count = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
      
    end
  end

  def edit
    
    book = Book.find(params[:id])
    unless book.user == current_user
      redirect_to '/books'
    end
    
    
    @book = Book.find(params[:id])
    
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have Updated book successfully."
    else
      render "edit"
    end
  end
    
  def destroy
    
    book = Book.find(params[:id])
    
    book.destroy

    redirect_to '/books'
    
  end

  private

  def book_params

    params.require(:book).permit(:title, :body)
  end
  
    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_comment.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= image_tag book_comment.user.get_profile_image, size:"100x100" %>
        <%= book_comment.comment %>
        <% if current_user == book_comment.user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), remote: true, method: :delete, class: "btn btn-sm btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>  
<div>
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5' %>
  <%= f.submit "送信" %>
<% end %>  
</div>
    
   
 

app/views/books/_counter.html.erb
コメント数:<%= book.book_comments.count %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id= "favorite_buttons_<%= book.id %>">
          <%= render "/favorites/favorites", book: book %>
        </td>
        <td><%= render "books/counter", book: book %></td>
        <td>閲覧数：<%= book.read_counts.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		
  		<%= render '/layouts/errors.html.erb', obj: @book %>
  		
  		<%= form_with model:@book,local:true do |f| %>
  　　<div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group">
      <%= f.submit "Update Book", class: 'btn btn-success' %>
      </div>
      <% end %>
  		
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<h3>

  <% if @book.errors.any? %>

    <%= @book.errors.count %> errors prohibited this obj from being saved:
  
    <ul>
  
      <% @book.errors.full_messages.each do |message| %>
  
        <li><%= message %></li>
    
      <% end %>
  
    </ul>

  <% end %>

</h3>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user, isRoom: @isRoom, room: @room, roomId: @roomId, entry: @entry %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div id= "index_books">
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user, isRoom: @isRoom, room: @room, roomId: @roomId, entry: @entry %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          
          <td id= "favorite_buttons_<%= @book.id %>">
            <%= render "/favorites/favorites", book: @book %>
          </td>
          
          <td id= "comment_count_<%= @book.id %>">
            <%= render "counter", book: @book %>
          </td>  
          <td>閲覧数：<%= @book.read_counts.count %></td>
          
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削しますか？" %></td>
        </tr>
          <% end %>
      </table>
      <div id= "commented_<%= @book.id %>">
        <%= render "book_comment", book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>